"""Generate docs/question-test-coverage.md from the catalog.

Written rather than hand-maintained for one reason: a coverage matrix exists to
show where documentation outruns testing, and a hand-maintained one drifts in
exactly the direction that hides the answer. Run it after editing the catalog:

    python tests/use_cases/build_coverage.py
"""

from __future__ import annotations

import json
from collections import Counter
from pathlib import Path

HERE = Path(__file__).resolve().parent
CATALOG = json.loads((HERE / "question_catalog.json").read_text(encoding="utf-8"))
OUT = HERE.parents[1] / "docs" / "question-test-coverage.md"

#: Which questions the end-to-end suite actually drives. Kept in step with
#: E2E_IDS in test_catalog_e2e.py; the check below fails the build if it drifts.
E2E_IDS = {
    "Q-SMALL-001", "Q-DATA-001", "Q-HIST-001", "Q-RISK-001", "Q-RISK-002",
    "Q-KNOW-002", "Q-HYBRID-001", "Q-ELICIT-002", "Q-UNSUP-001", "Q-UNSUP-003",
}

TICK, CROSS = "yes", "—"


def deterministic_cover(q: dict) -> tuple[bool, bool]:
    """(unit, integration) coverage from `test_question_catalog.py`.

    Unit — every question is checked for shape, legal enums, a stated reason and
    an honesty assertion. Integration — a question is covered when a live store
    or the MCP stack is consulted on its behalf: its data facts, its knowledge
    documents, its named tool, or its ground truth.
    """
    unit = True
    integration = bool(
        q.get("ground_truth")
        or q.get("knowledge_documents")
        or q.get("expected_tools")
        or q["category"] in {"basic_data_lookup", "historical", "yield_curve_analysis",
                             "error_edge_case", "metadata_catalogue"})
    return unit, integration


def main() -> None:
    questions = CATALOG["questions"]
    facts = CATALOG["data_facts"]

    stray = E2E_IDS - {q["id"] for q in questions}
    if stray:
        raise SystemExit(f"E2E_IDS names questions absent from the catalog: {sorted(stray)}")

    lines: list[str] = []
    add = lines.append

    add("# Question / test coverage matrix")
    add("")
    add("**semantic-mcp-data-access-gateway** — generated by "
        "`tests/use_cases/build_coverage.py`. Do not edit by hand.")
    add("")
    add("Source of truth: [`tests/use_cases/question_catalog.json`]"
        "(../tests/use_cases/question_catalog.json). "
        "Prose: [`supported-question-catalog.md`](supported-question-catalog.md).")
    add("")
    add("`Unit` and `Integration` are provided by "
        "`tests/use_cases/test_question_catalog.py`, which needs no language "
        "model — every fact below is re-derived from PostgreSQL, Qdrant and the "
        "live MCP servers. `E2E` is `tests/use_cases/test_catalog_e2e.py`, which "
        "drives a representative slice through `/chat` and skips when the "
        "backend or the model is unreachable.")
    add("")

    supported = Counter(q["supported"] for q in questions)
    add("## Totals")
    add("")
    add(f"- **{len(questions)}** questions across **"
        f"{len({q['category'] for q in questions})}** categories")
    add(f"- Supported **{supported['YES']}** · "
        f"Partial **{supported['PARTIAL']}** · Unsupported **{supported['NO']}**")
    add(f"- End-to-end slice: **{len(E2E_IDS)}** questions")
    add("")

    add("## By category")
    add("")
    add("| Category | Questions | YES | PARTIAL | NO | E2E |")
    add("|---|---:|---:|---:|---:|---:|")
    for category in sorted({q["category"] for q in questions}):
        group = [q for q in questions if q["category"] == category]
        counts = Counter(q["supported"] for q in group)
        e2e = sum(1 for q in group if q["id"] in E2E_IDS)
        add(f"| {category.replace('_', ' ')} | {len(group)} | {counts['YES']} "
            f"| {counts['PARTIAL']} | {counts['NO']} | {e2e} |")
    add("")

    add("## Every question")
    add("")
    add("| ID | Category | PG | Qdrant | Domain expert | MCP agent | Tool | Elicit "
        "| Unit | Integ | E2E | Supported |")
    add("|---|---|:-:|:-:|:-:|:-:|---|:-:|:-:|:-:|:-:|---|")
    for q in questions:
        unit, integration = deterministic_cover(q)
        agents = q["expected_agents"]
        tools = ", ".join(q["expected_tools"]) or CROSS
        add("| `{id}` | {cat} | {pg} | {qd} | {de} | {mcp} | {tool} | {el} "
            "| {u} | {i} | {e} | {sup} |".format(
                id=q["id"], cat=q["category"].replace("_", " "),
                pg=TICK if "postgres" in q["sources"] else CROSS,
                qd=TICK if "qdrant" in q["sources"] else CROSS,
                de=TICK if "domain-expert" in agents else CROSS,
                mcp=TICK if "mcp-agent" in agents else CROSS,
                tool=tools,
                el=TICK if q["requires_elicitation"] else CROSS,
                u=TICK if unit else CROSS,
                i=TICK if integration else CROSS,
                e=TICK if q["id"] in E2E_IDS else CROSS,
                sup=q["supported"]))
    add("")

    add("## Where documentation outruns testing")
    add("")
    gaps = [q for q in questions
            if q["supported"] in {"YES", "PARTIAL"}
            and q["id"] not in E2E_IDS
            and not deterministic_cover(q)[1]]
    if gaps:
        add("These are documented as supported but are only covered by the "
            "catalog-integrity checks — no live store or service is consulted "
            "on their behalf:")
        add("")
        for q in gaps:
            add(f"- `{q['id']}` — {q['question']}")
    else:
        add("Every supported or partially supported question is covered by at "
            "least one test that consults a live store, the MCP stack, or the "
            "running service.")
    add("")

    add("## Known defects")
    add("")
    for defect in CATALOG["known_defects"]:
        add(f"### {defect['id']} — {defect['title']}")
        add("")
        add(f"- **Classification:** `{defect['classification']}`")
        add(f"- **Affects:** {', '.join('`' + a + '`' for a in defect['affects'])}")
        add(f"- **Status:** reported, not fixed" if defect.get("reported_not_fixed")
            else "- **Status:** fixed")
        add("")
        add(f"**What was wrong.** {defect['detail']}")
        add("")
        if defect.get("fix"):
            # The defect text stays in the present tense on purpose: it is the
            # reproduction, and rewriting it to the past would make the record
            # unusable for checking that the fix addresses what was reported.
            add(f"**Fix.** {defect['fix']}")
            add("")

    add("## Data the matrix was built against")
    add("")
    add(f"- PostgreSQL — {facts['observation_rows']:,} observations, "
        f"{facts['series_count']} series, {facts['earliest_observation']} to "
        f"{facts['latest_observation']}")
    add(f"- Qdrant — `{facts['qdrant_collection']}`, {facts['qdrant_points']} chunks "
        f"across {len(facts['qdrant_documents'])} documents")
    add(f"- Demo book — `{facts['portfolio_id']}`, {facts['portfolio_positions']} "
        f"positions, {len(facts['scenario_ids'])} scenarios")
    add("")
    add("These figures are asserted against the live stores by "
        "`test_data_facts_still_match_the_database`, so this file cannot quietly "
        "describe a database that no longer exists.")
    add("")

    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT.relative_to(HERE.parents[1])} "
          f"({len(questions)} questions, {len(lines)} lines)")


if __name__ == "__main__":
    main()
